### ISSUE TITLE
Comment syntax is unclear

### ISSUE THREAD

**Issue by st-pasha** [jgm/djot#252] opened 2023-10-25 21:09 UTC
The syntax spec seems to suggest that a comment can be added by surrounding it with `{% ... %}`. However, in the playground the following doesn't work:
```djot
{% 
Paragraph 1

Paragraph 2
%}
```
In this example both `{%` and `%}` currently render verbatim.

It appears that the comment only works if both the opening `{%` and closing `%}` are on the same line. I think that this is too restrictive. In practice, larger comments may be needed in a document in some cases:
- In order to insert a copyright/license notice;
- In order to temporarily comment-out some large chunks of the document because there's something wrong with them;
- Add documentation to parts of document (not particularly common, but sometimes necessary, eg: "If you add or modify entries in this table, then make sure to ...").

Also, somehow this is not a comment at all?
```
{% Paragraph {% ! %} one %}
```

**Comment by jgm** [comment] 2023-10-25 22:52
Duplicate of #67

**Closed by jgm** 2023-10-25 22:52 UTC
